server:
  port: 8083
spring:
  application:
    name: twitter-clone-likes-service
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      uri: ${DB_URL:mongodb://localhost:27017/tc_likes_db}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:1234}
users-service:
  url: ${USERS_URL:http://localhost:8080/users}
posts-service:
  url: ${POSTS_URL:http://localhost:8081/posts}
comments-service:
  url: ${COMMENTS_URL:http://localhost:8082/comments}